### PR TITLE
Preserve back key navigation

### PR DESCRIPTION
**Pull request by buttercookie42**
Pass the id of the currently selected tab when opening a new tab, so that pressing the back key correctly returns to the previous tab instead of closing Firefox.

### CODE REVIEW

**Comment by ispedals** [comment]
I haven't been able to have the search results show up when performing the search in quite some time. Are you able to successfully complete a search?

**Comment by buttercookie42** [comment]
Yes, but only by temporarily faking my user agent while doing Google searches (and then not forgetting to put it back, as Firefox's market share on mobile is unfortunately already low enough as it is ;-) ). In that case, your add-on works fine.

Basically it's Google's fault, they're redirecting mobile Firefox users to a less fancy version of their search, which unfortunately doesn't include neither search filtering, the new image search, or reverse image search.
There are some web evangelism bugs on Bugzilla, most relevant is [bug 1200652](https://bugzilla.mozilla.org/show_bug.cgi?id=1200652), but also [bug 1047854](https://bugzilla.mozilla.org/show_bug.cgi?id=1047854) and [bug 921532](https://bugzilla.mozilla.org/show_bug.cgi?id=921532).
But as Google seems to move at a glacial speed as far as changing their browser-sniffing behaviour is concerned, who knows when this will finally get fixed...

**Comment by buttercookie42** [comment]
Thanks :-)

**Comment by ispedals** [comment]
Thanks for the tip about the user agent, I've updated the addon to change the user agent when needed.

**Comment by buttercookie42** [comment]
Looks nice, although the override doesn't cover all reverse image search related pages, e.g. "find other sizes" and "visually similar images" don't quite work yet. If you'll update the source code here to the version from AMO, I can take a look and send you another pull request.

**Comment by ispedals** [comment]
Sorry, I thought I pushed. Thanks!

**Pull request merged**
